# Costs (multipliers of residuals) of the measurements added to factor graph (used when fuse_icp is true).

c_odom_default: 0.05  # Cost for odometry measurements without valid covariance.
c_odom_scale: 0.01  # Cost for odometry measurements with valid covariance (cost = scale / sqrt(covariance)).
c_odom_bumper: 0  # Cost for odometry measurements when bumper was active.
c_icp_default: 2.0  # Cost for ICP odometry measurements without valid covariance.
c_icp_scale: 0.1  # Cost for ICP odometry measurements with valid covariance (cost = scale / sqrt(covariance)).
c_icp_yaw_scale: 1.5  # Extra multiplier for yaw in ICP odometry cost.
c_mr_scale: 0.5  # Cost of the relative marker observation (cost ~= scale * (max_dist - dist) / (max_dist + 0.1)).
c_ma_scale: 1.0  # Cost of the absolute marker observation (cost ~= scale * (max_dist - dist) / (max_dist + 0.1)).
c_marker_yaw_scale: 1.  # Extra multiplier for yaw in marker observations.
